version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5099:5099" 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__postgreSQL: "Host=db;Port=5432;Username=postgres;Password=root;Database=postgres;Trust Server Certificate=true;"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
